version: "3.8"

services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: alwani
        MONGO_INITDB_ROOT_PASSWORD: alwani
        MONGO_INITDB_ROOT_DATABASE: admin
    networks: 
      - network-example

networks:
  network-example:
    name: network-example
    driver: bridge
    
